// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrZiG9VcK9c-x-HpCdQDRW_mRXBu9ft08',
    appId: '1:366669196040:web:a9c50524291de1a4e35abd',
    messagingSenderId: '366669196040',
    projectId: 'delevery-app-b8407',
    authDomain: 'delevery-app-b8407.firebaseapp.com',
    storageBucket: 'delevery-app-b8407.appspot.com',
    measurementId: 'G-0KNQCEVCEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbgOvz2Gq6McfW42X_-b-ykDCZ--vjQXw',
    appId: '1:366669196040:android:8a1d005b537005cce35abd',
    messagingSenderId: '366669196040',
    projectId: 'delevery-app-b8407',
    storageBucket: 'delevery-app-b8407.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDFvp3J2CXAh6nkIpc9l6ygJSHnHBfW6I',
    appId: '1:366669196040:ios:950b4adc39229092e35abd',
    messagingSenderId: '366669196040',
    projectId: 'delevery-app-b8407',
    storageBucket: 'delevery-app-b8407.appspot.com',
    iosClientId: '366669196040-k6ke2bapu8ri0mogqba4o1asnbqj6f8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.magazine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDFvp3J2CXAh6nkIpc9l6ygJSHnHBfW6I',
    appId: '1:366669196040:ios:9fc770fd3f600b8be35abd',
    messagingSenderId: '366669196040',
    projectId: 'delevery-app-b8407',
    storageBucket: 'delevery-app-b8407.appspot.com',
    iosClientId: '366669196040-litgtmdj4rdnqofnvjord0sqmm9incsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.magazine.RunnerTests',
  );
}
